# Generated by Django 2.2.19 on 2023-07-06 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etgb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('url', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Таможенная декларация',
                'verbose_name_plural': 'Таможенные декларации',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Etgb_of_posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_number', models.TextField(unique=True)),
                ('etgb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etgb', to='posting.Etgb', verbose_name='Декларация')),
            ],
            options={
                'verbose_name': 'Таможенная декларация отправленной посылки',
                'verbose_name_plural': 'Таможенные декларации отправленных посылок',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='etgb',
            constraint=models.UniqueConstraint(fields=('number', 'url'), name='uniq_etgb'),
        ),
        migrations.AddConstraint(
            model_name='etgb_of_posting',
            constraint=models.UniqueConstraint(fields=('posting_number', 'etgb'), name='uniq_etgb_of_posting'),
        ),
    ]
