# Generated by Django 3.2 on 2023-07-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etgb',
            name='number',
            field=models.TextField(default='05070543901819148520486120195647', unique=True),
        ),
        migrations.AlterField(
            model_name='etgb',
            name='url',
            field=models.SlugField(default='74OwhLpWHylezlds0aR91boqbJfj5anf', unique=True),
        ),
        migrations.AlterField(
            model_name='etgb_of_posting',
            name='posting_number',
            field=models.TextField(default='66551444486065110601187778214959', unique=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='api_key',
            field=models.CharField(default='p7Pi4dyAcNK2vGgOPB6qA5CGCQ5K1Qne', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='client_id',
            field=models.CharField(default='10173997629144468633863476590650', max_length=256, unique=True),
        ),
    ]
